In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
# fuzz is used to compare TWO strings
from fuzzywuzzy import fuzz
# process is used to compare a string to MULTIPLE other strings
from fuzzywuzzy import process
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from numpy import loadtxt
from numpy import savetxt

/opt/homebrew/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
/opt/homebrew/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
df=pd.read_csv('Dataset/string_ingredients.csv')
#df.sample(10)  randomly ouputs 10 sample

In [3]:
bert = SentenceTransformer('bert-base-nli-mean-tokens')

In [4]:
## Helper function to retrieve receipes

def get_index(recp):
    return df[df.TranslatedRecipeName == recp].index.values[0]

def get_receipe(index):
    return df[df.index == index]["TranslatedRecipeName"].values[0]

In [5]:
sentence_embeddings = bert.encode(df['parsed']).tolist()

In [6]:
similarity = cosine_similarity(sentence_embeddings)

In [7]:
savetxt('similarity_scores.csv', similarity, delimiter=',')

In [8]:
sim_score = loadtxt('similarity_scores.csv', delimiter=',')
# print the array
print(sim_score)

[[1.         0.90637215 0.87435139 ... 0.76991729 0.95902865 0.83062583]
 [0.90637215 1.         0.92769798 ... 0.73218657 0.93576689 0.88795622]
 [0.87435139 0.92769798 1.         ... 0.68437122 0.90542273 0.85009461]
 ...
 [0.76991729 0.73218657 0.68437122 ... 1.         0.72389932 0.68523532]
 [0.95902865 0.93576689 0.90542273 ... 0.72389932 1.         0.86546365]
 [0.83062583 0.88795622 0.85009461 ... 0.68523532 0.86546365 1.        ]]


In [9]:
def getRecipeRecommentation(recipe_name):
    return sorted(list(enumerate(sim_score[get_index(recipe_name)])), key = lambda x: x[1], reverse=True)

In [14]:
possibilities = process.extract("Basundi", df['TranslatedRecipeName'], limit=1, scorer=fuzz.UQRatio)
recommendations = getRecipeRecommentation(possibilities[0][0])
for x in range(10):
    print(get_receipe(recommendations[x][0]), sep = "\n")

Basundi / Rabri Recipe
Sindhi Kheerni Recipe - Sindhi Seviyan Kheer
Kesar Pista Kulfi Recipe
No Bake Rice Mawa Cake Recipe
Sheer Khurma Recipe - Seviyan or Vermicelli Kheer Pudding
Almond Elachi Kulfi Recipe
Nariyal Ki Kheer Recipe - Coconut Pudding
Kesar Elaichi Shrikand Recipe
Saffron Pistachio Firni Recipe
Chicken Pies Recipe
